services:
  - type: web
    name: epl-player-search
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential python3-dev
      pip install --upgrade pip
      pip install wheel setuptools
      pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.15
      - key: SECRET_KEY
        generateValue: true
      - key: KAGGLE_USERNAME
        sync: false
      - key: KAGGLE_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: epl_db
          property: connectionString
    buildEnv:
      - key: PYTHON_VERSION
        value: 3.9.15
      - key: DEBIAN_FRONTEND
        value: noninteractive

databases:
  - name: epl_db
    databaseName: epl_player_search
    user: epl_admin 